version: '3.4'
      
services:             
  test-task-api:
    image: messagesenderserviceapi:v0.001
    restart: unless-stopped
    expose:
      - "80" 
    ports:
      - "6080:80"   
    networks:
      - test-task-net
    depends_on:
      - test-task-db

  test-task-db:
    image: postgres:14.2
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
    ports:
       - "6034:5432"
    expose:
       - "5432"
    networks:
      - test-task-net
    volumes:
       - ./pgdata:/var/lib/postgresql/data 
      
networks:
  test-task-net:
    external: true